[development]
USEDOCKER = false
#MONGO_DB_HOST="@format {env[LOCALIP]}"
#MONGO_DB_HOST="192.168.12.19"
MONGO_DB_HOST="127.0.0.1"
MONGO_DB_PORT=27019
ADDRESSES_PATH="."
ANALYTICS_PATH="."
NO_OAUTH = 1
PLAYIPAPP_URL = "@format http://{env[LOCALIP]}:8009"
TEST = 1


[testing]
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
ADDRESSES_PATH="/etc"
ANALYTICS_PATH="/etc"
NO_OAUTH = 0
PLAYIPAPP_URL = "http://apphub:8008"

[prodtemp]
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
ADDRESSES_PATH="/etc"
ANALYTICS_PATH="/etc"
NO_OAUTH = 0
PLAYIPAPP_URL = "http://apphub:8008"

[production]
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
ADDRESSES_PATH="/etc"
ANALYTICS_PATH="/etc"
NO_OAUTH = 0
PLAYIPAPP_URL = "http://apphub:8008"