[development]
USEDOCKER = false
MONGO_DB_HOST="192.168.12.59"
MONGO_DB_PORT=27017
ADDRESSES_PATH="."
ANALYTICS_PATH="."

[testing]
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
ADDRESSES_PATH="/etc"
ANALYTICS_PATH="/etc"

[prodtemp]
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
ADDRESSES_PATH="/etc"
ANALYTICS_PATH="/etc"

[production]
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
ADDRESSES_PATH="/etc"
ANALYTICS_PATH="/etc"